name: Extract and cite

on:
  issues:
    types: [opened]

jobs:
  extract-info:
    runs-on: ubuntu-latest
    steps:
    - name: Find all papers
        id: paper
        uses: lee-dohm/select-matching-issues@v1
        with:
          query: 'label:paper'
          token: ${{ secrets.GITHUB_TOKEN }}
